import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import "./meanmenu.min.css";
import Footter from "@/component/footter/Footter";
import Navbar from "@/component/Navbar";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "best-Gym",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className=" mx-0 sm:mx-[0px] lg:mx-[70px]">
        <Navbar></Navbar>
        {children}
        {/* <Footter></Footter> */}
      </body>
    </html>
  );
}
